import { Montserrat } from "next/font/google";
import "./globals.css";

import BackgroundBorder from "./components/BackgroundBorder";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/navbar/Navbar";

const montserrat = Montserrat({
  subsets: ["vietnamese"],
  weight: "200",
});

export const metadata = {
  title: "Mike Padial - Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="overflow-hidden p-0 m-0 box-border flex w-screen min-h-screen text-slate-300">
        <div
          className="flex items-center justify-center min-h-full w-full  
            bg-gradient-to-br 
            from-sky-950 
            via-gray-800
            to-emerald-950
            animate-gradient-x"
        >
          <BackgroundBorder>
            <Sidebar />
            {children}
          </BackgroundBorder>
        </div>
      </body>
    </html>
  );
}
